### ISSUE TITLE
Instance ref template: "_Monograph Work (BF2) Un-Nested" for MARC conversion (https://)

### ISSUE THREAD

**Issue by jimfhahn** [LD4P/rdf2marc#9] opened 2020-09-23 15:01 UTC
Hello, I was working in Sinopia stage and noticed that my Instance ( https://api.stage.sinopia.io/resource/29dc2e6e-02d0-407d-8067-d4c78db6f19c ) would not convert to MARC if I referenced the template "_Monograph Work (BF2) Un-Nested for MARC conversion" -- I was comparing this against the terminal code and found that if I change all the http:// to https:// in the Work record, then it converts, with some missing literals.

However, I do see the output MARC seems to skip over what I referenced, so I'm confused as to what I'm seeing.

Ex. if the Instance references this work, it will throw an error in conversion:

<https://api.stage.sinopia.io/resource/28d35bb9-9fd1-4f07-a3da-a45a9b703f8e> <http://sinopia.io/vocabulary/hasResourceTemplate> "ld4p:RT:bf2:Monograph:Work:Un-nested";
    a <http://id.loc.gov/ontologies/bibframe/Work>;
    <http://id.loc.gov/ontologies/bibframe/contribution> _:b257.
_:b257 a <http://id.loc.gov/ontologies/bflc/PrimaryContribution>;
    <http://id.loc.gov/ontologies/bibframe/agent> _:b258.
_:b258 a <http://id.loc.gov/ontologies/bibframe/Person>;
    <http://www.w3.org/1999/02/22-rdf-syntax-ns#value> "Mařák, Jindřich".
_:b257 <http://id.loc.gov/ontologies/bibframe/role> <http://id.loc.gov/vocabulary/relators/aut>.
<http://id.loc.gov/vocabulary/relators/aut> <http://www.w3.org/2000/01/rdf-schema#label> "Author".
<https://api.stage.sinopia.io/resource/28d35bb9-9fd1-4f07-a3da-a45a9b703f8e> <http://id.loc.gov/ontologies/bibframe/title> _:b259.
_:b259 a <http://id.loc.gov/ontologies/bibframe/Title>;
    <http://id.loc.gov/ontologies/bibframe/mainTitle> "Nezabiješ!"@eng.
<https://api.stage.sinopia.io/resource/28d35bb9-9fd1-4f07-a3da-a45a9b703f8e> <http://id.loc.gov/ontologies/bibframe/originPlace> "United States";
    <http://id.loc.gov/ontologies/bibframe/temporalCoverage> "1919"@eng;
    <http://id.loc.gov/ontologies/bibframe/note> _:b260.
_:b260 a <http://id.loc.gov/ontologies/bibframe/Note>;
    <http://www.w3.org/2000/01/rdf-schema#label> "The novel is accompanied by informational text about the I.W.W."@eng.
<https://api.stage.sinopia.io/resource/28d35bb9-9fd1-4f07-a3da-a45a9b703f8e> <http://id.loc.gov/ontologies/bibframe/summary> _:b261.
_:b261 a <http://id.loc.gov/ontologies/bibframe/Summary>;
    <http://www.w3.org/2000/01/rdf-schema#label> "A novelized account of Wesley Everest, an I.W.W. worker who was lynched during the Centralia massacre of 1919."@eng.
<https://api.stage.sinopia.io/resource/28d35bb9-9fd1-4f07-a3da-a45a9b703f8e> <http://id.loc.gov/ontologies/bibframe/classification> _:b262.
_:b262 a <http://id.loc.gov/ontologies/bibframe/ClassificationLcc>;
    <http://id.loc.gov/ontologies/bibframe/classificationPortion> "PG5069.M35"@eng;
    <http://id.loc.gov/ontologies/bibframe/itemPortion> "N49 1929z"@eng.
<https://api.stage.sinopia.io/resource/28d35bb9-9fd1-4f07-a3da-a45a9b703f8e> <http://id.loc.gov/ontologies/bibframe/content> <http://id.loc.gov/vocabulary/contentTypes/txt>.
<http://id.loc.gov/vocabulary/contentTypes/txt> <http://www.w3.org/2000/01/rdf-schema#label> "text".
<https://api.stage.sinopia.io/resource/28d35bb9-9fd1-4f07-a3da-a45a9b703f8e> <http://id.loc.gov/ontologies/bibframe/language> <http://id.loc.gov/vocabulary/languages/cze>.
<http://id.loc.gov/vocabulary/languages/cze> <http://www.w3.org/2000/01/rdf-schema#label> "Czech".
<https://api.stage.sinopia.io/resource/28d35bb9-9fd1-4f07-a3da-a45a9b703f8e> <http://id.loc.gov/ontologies/bibframe/notation> _:b263.
_:b263 a <http://id.loc.gov/ontologies/bibframe/Script>;
    <http://www.w3.org/2000/01/rdf-schema#label> "Latin"@eng.
<https://api.stage.sinopia.io/resource/28d35bb9-9fd1-4f07-a3da-a45a9b703f8e> <http://id.loc.gov/ontologies/bibframe/illustrativeContent> <http://id.loc.gov/vocabulary/millus/ill>.
<http://id.loc.gov/vocabulary/millus/ill> <http://www.w3.org/2000/01/rdf-schema#label> "Illustrations".
<https://api.stage.sinopia.io/resource/28d35bb9-9fd1-4f07-a3da-a45a9b703f8e> <http://id.loc.gov/ontologies/bibframe/illustrativeContent> <http://id.loc.gov/vocabulary/millus/por>.
<http://id.loc.gov/vocabulary/millus/por> <http://www.w3.org/2000/01/rdf-schema#label> "Portraits".
<https://api.stage.sinopia.io/resource/28d35bb9-9fd1-4f07-a3da-a45a9b703f8e> <http://id.loc.gov/ontologies/bibframe/colorContent> <http://id.loc.gov/vocabulary/mcolor/blw>.
<http://id.loc.gov/vocabulary/mcolor/blw> <http://www.w3.org/2000/01/rdf-schema#label> "black and white".
<https://api.stage.sinopia.io/resource/28d35bb9-9fd1-4f07-a3da-a45a9b703f8e> <http://id.loc.gov/ontologies/bibframe/hasInstance> <https://api.stage.sinopia.io/resource/29dc2e6e-02d0-407d-8067-d4c78db6f19c>.
<https://api.stage.sinopia.io/resource/29dc2e6e-02d0-407d-8067-d4c78db6f19c> <http://www.w3.org/2000/01/rdf-schema#label> "https://api.stage.sinopia.io/resource/29dc2e6e-02d0-407d-8067-d4c78db6f19c".

Ex. however, it seems this will convert as expected in the terminal:

<https://api.stage.sinopia.io/resource/28d35bb9-9fd1-4f07-a3da-a45a9b703f8e> <https://sinopia.io/vocabulary/hasResourceTemplate> "ld4p:RT:bf2:Monograph:Work:Un-nested";
    a <https://id.loc.gov/ontologies/bibframe/Work>;
    <https://id.loc.gov/ontologies/bibframe/contribution> _:b243.
_:b243 a <https://id.loc.gov/ontologies/bflc/PrimaryContribution>;
    <https://id.loc.gov/ontologies/bibframe/agent> _:b244.
_:b244 a <https://id.loc.gov/ontologies/bibframe/Person>;
    <https://www.w3.org/1999/02/22-rdf-syntax-ns#value> "Mařák, Jindřich".
_:b243 <https://id.loc.gov/ontologies/bibframe/role> <https://id.loc.gov/vocabulary/relators/aut>.
<https://id.loc.gov/vocabulary/relators/aut> <https://www.w3.org/2000/01/rdf-schema#label> "Author".
<https://api.stage.sinopia.io/resource/28d35bb9-9fd1-4f07-a3da-a45a9b703f8e> <https://id.loc.gov/ontologies/bibframe/title> _:b245.
_:b245 a <https://id.loc.gov/ontologies/bibframe/Title>;
    <https://id.loc.gov/ontologies/bibframe/mainTitle> "Nezabiješ!"@eng.
<https://api.stage.sinopia.io/resource/28d35bb9-9fd1-4f07-a3da-a45a9b703f8e> <https://id.loc.gov/ontologies/bibframe/originPlace> "United States";
    <https://id.loc.gov/ontologies/bibframe/temporalCoverage> "1919"@eng;
    <https://id.loc.gov/ontologies/bibframe/note> _:b246.
_:b246 a <https://id.loc.gov/ontologies/bibframe/Note>;
    <https://www.w3.org/2000/01/rdf-schema#label> "The novel is accompanied by informational text about the I.W.W."@eng.
<https://api.stage.sinopia.io/resource/28d35bb9-9fd1-4f07-a3da-a45a9b703f8e> <https://id.loc.gov/ontologies/bibframe/summary> _:b247.
_:b247 a <https://id.loc.gov/ontologies/bibframe/Summary>;
    <https://www.w3.org/2000/01/rdf-schema#label> "A novelized account of Wesley Everest, an I.W.W. worker who was lynched during the Centralia massacre of 1919."@eng.
<https://api.stage.sinopia.io/resource/28d35bb9-9fd1-4f07-a3da-a45a9b703f8e> <https://id.loc.gov/ontologies/bibframe/classification> _:b248.
_:b248 a <https://id.loc.gov/ontologies/bibframe/ClassificationLcc>;
    <https://id.loc.gov/ontologies/bibframe/classificationPortion> "PG5069.M35"@eng;
    <https://id.loc.gov/ontologies/bibframe/itemPortion> "N49 1929z"@eng.
<https://api.stage.sinopia.io/resource/28d35bb9-9fd1-4f07-a3da-a45a9b703f8e> <https://id.loc.gov/ontologies/bibframe/content> <https://id.loc.gov/vocabulary/contentTypes/txt>.
<https://id.loc.gov/vocabulary/contentTypes/txt> <https://www.w3.org/2000/01/rdf-schema#label> "text".
<https://api.stage.sinopia.io/resource/28d35bb9-9fd1-4f07-a3da-a45a9b703f8e> <https://id.loc.gov/ontologies/bibframe/language> <https://id.loc.gov/vocabulary/languages/cze>.
<https://id.loc.gov/vocabulary/languages/cze> <https://www.w3.org/2000/01/rdf-schema#label> "Czech".
<https://api.stage.sinopia.io/resource/28d35bb9-9fd1-4f07-a3da-a45a9b703f8e> <https://id.loc.gov/ontologies/bibframe/notation> _:b249.
_:b249 a <https://id.loc.gov/ontologies/bibframe/Script>;
    <https://www.w3.org/2000/01/rdf-schema#label> "Latin"@eng.
<https://api.stage.sinopia.io/resource/28d35bb9-9fd1-4f07-a3da-a45a9b703f8e> <https://id.loc.gov/ontologies/bibframe/illustrativeContent> <https://id.loc.gov/vocabulary/millus/ill>.
<https://id.loc.gov/vocabulary/millus/ill> <https://www.w3.org/2000/01/rdf-schema#label> "Illustrations".
<https://api.stage.sinopia.io/resource/28d35bb9-9fd1-4f07-a3da-a45a9b703f8e> <https://id.loc.gov/ontologies/bibframe/illustrativeContent> <https://id.loc.gov/vocabulary/millus/por>.
<https://id.loc.gov/vocabulary/millus/por> <https://www.w3.org/2000/01/rdf-schema#label> "Portraits".
<https://api.stage.sinopia.io/resource/28d35bb9-9fd1-4f07-a3da-a45a9b703f8e> <https://id.loc.gov/ontologies/bibframe/colorContent> <https://id.loc.gov/vocabulary/mcolor/blw>.
<https://id.loc.gov/vocabulary/mcolor/blw> <https://www.w3.org/2000/01/rdf-schema#label> "black and white".
<https://api.stage.sinopia.io/resource/28d35bb9-9fd1-4f07-a3da-a45a9b703f8e> <https://id.loc.gov/ontologies/bibframe/hasInstance> <https://api.stage.sinopia.io/resource/29dc2e6e-02d0-407d-8067-d4c78db6f19c>.
<https://api.stage.sinopia.io/resource/29dc2e6e-02d0-407d-8067-d4c78db6f19c> <https://www.w3.org/2000/01/rdf-schema#label> "https://api.stage.sinopia.io/resource/29dc2e6e-02d0-407d-8067-d4c78db6f19c".

**Comment by justinlittman** [comment] 2020-09-29 02:19
Thanks for reporting @jimfhahn. I took a look at this, but wasn't entirely clear how to replicate. Do you mind proving specific steps to reproduce the problem?

Additionally: When I ran from the commandline, I received:
```
$ exe/rdf2marc  https://api.stage.sinopia.io/resource/29dc2e6e-02d0-407d-8067-d4c78db6f19c
Traceback (most recent call last):
	6: from exe/rdf2marc:21:in `<main>'
	5: from /Users/jlittman/data/ld4p/rdf2marc/lib/rdf2marc/rdf2model.rb:12:in `to_model'
	4: from /Users/jlittman/data/ld4p/rdf2marc/lib/rdf2marc/rdf2model/mapper.rb:12:in `generate'
	3: from /Users/jlittman/data/ld4p/rdf2marc/lib/rdf2marc/rdf2model/mappers/main_entry_fields.rb:10:in `generate'
	2: from /Users/jlittman/data/ld4p/rdf2marc/lib/rdf2marc/rdf2model/mappers/main_entry_fields.rb:20:in `main_personal_name'
	1: from /Users/jlittman/data/ld4p/rdf2marc/lib/rdf2marc/graph_query.rb:28:in `path_first_uri'
/Users/jlittman/data/ld4p/rdf2marc/lib/rdf2marc/graph_query.rb:91:in `to_uri': Not a URI (Rdf2marc::MappingError)
```

That problem seems to be because the primary contributor is a literal, not a URI:
```
{
      "@id": "_:b237",
      "@type": [
        "http://id.loc.gov/ontologies/bibframe/Person"
      ],
      "http://www.w3.org/1999/02/22-rdf-syntax-ns#value": [
        {
          "@value": "Mařák, Jindřich"
        }
      ]
    }
```

**Comment by jimfhahn** [comment] 2020-09-29 16:18
Ok, that helps. I don't think I understand literal requirements. Does this mean if the contributor name is not in id.loc.gov it cannot convert? 

I realize now that my question here is kind of lost in the weeds due to my own debugging rabbit hole. I suppose my broader question is why the instance will not generate MARC when it seems to have the required aspects of the converter: 

Must reference a Bibframe Work or nest a Bibframe Work via a blank node.
Must reference Admin Metadata or nest Admin Metadata via a blank node.

![image](https://user-images.githubusercontent.com/1310509/94585079-1dbf3000-0245-11eb-84a6-b0e50e8de4d9.png)

**Comment by justinlittman** [comment] 2020-09-30 11:58
> Does this mean if the contributor name is not in id.loc.gov it cannot convert?

Yes, that is the current functionality of rdf2marc. There is a discussion of this in https://github.com/LD4P/sinopia_editor/issues/2530 you might be interested in.

**Comment by justinlittman** [comment] 2020-10-06 19:19
I've made changes in rdf2marc so that it will accept literals in some places where URIs are expected. Let me know if this addresses your problem.

**Comment by jimfhahn** [comment] 2020-10-06 21:11
Yes; that worked, thank you! In the future would it be possible to detail which literals are problematic when showing the "not a URI" message? Perhaps it would make more sense in Sinopia where the offending form element could be highlighted...

**Comment by justinlittman** [comment] 2020-10-07 11:19
Rdf2Marc is a completely separate library from Sinopia, so a bit hard to tie them together. However, definitely worth thinking about.

In general, literals for URIs are supported for any field in which the MARC field can be constructed without performing a lookup. Thus, for example, it is not supported for subject access fields because the literal cannot determine which MARC field to use.

Close this ticket or more to discuss?

**Comment by jimfhahn** [comment] 2020-10-07 12:58
Makes sense thank you @justinlittman. good to close...

**Closed** 2020-10-07 13:23 UTC
